// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Base: typeof import('./src/view/base/index.vue')['default']
    DiffAlgorithm: typeof import('./src/components/DiffAlgorithm.vue')['default']
    IssuesCloseOutlined: typeof import('@ant-design/icons-vue')['IssuesCloseOutlined']
    MehOutlined: typeof import('@ant-design/icons-vue')['MehOutlined']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MenuUnfoldOutlined: typeof import('@ant-design/icons-vue')['MenuUnfoldOutlined']
    Ref: typeof import('./src/components/Ref.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToRef: typeof import('./src/view/ref/toRef.vue')['default']
    UploadOutlined: typeof import('@ant-design/icons-vue')['UploadOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    VideoCameraOutlined: typeof import('@ant-design/icons-vue')['VideoCameraOutlined']
  }
}
